### ISSUE TITLE
Possible Code Improvement: Use `switch`-`case` Statements, Instead Of Chaining `if` Statements

### ISSUE THREAD

**Issue by HTGAzureX1212** [Reimnop/LearnInterpreter#1]
The following pieces of code contains a lot of chaining `if` statements. It is possible to improve on this code by using `switch`-`case` statements instead.

https://github.com/Reimnop/LearnInterpreter/blob/main/LearnInterpreter/Lexer.cs#L29-L115

**Comment by Reimnop** [comment]
Thanks for the feedback :)
